import React from "react";
import { ScrollView, StyleSheet, useWindowDimensions, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { IconButton, Text, useTheme } from "react-native-paper";
import { useNavigation } from "@react-navigation/native";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  const theme = useTheme();
  return (
    <View style={styles.section}>
      <Text
        variant="titleMedium"
        style={[styles.sectionTitle, { color: theme.colors.primary }]}
      >
        {title}
      </Text>
      {children}
    </View>
  );
}

function Para({ children }: { children: string }) {
  const theme = useTheme();
  return (
    <Text
      variant="bodyMedium"
      style={{ color: theme.colors.onSurface, lineHeight: 22 }}
    >
      {children}
    </Text>
  );
}

export function HelpScreen() {
  const theme = useTheme();
  const navigation = useNavigation();
  const insets = useSafeAreaInsets();
  const { width, height } = useWindowDimensions();
  const isLandscape = width > height;

  const topInset = isLandscape ? 0 : insets.top;
  const leftInset = isLandscape ? insets.left : 0;

  return (
    <View style={[styles.root, { backgroundColor: theme.colors.background }]}>
      <IconButton
        icon="arrow-left"
        size={24}
        onPress={() => navigation.goBack()}
        style={[
          styles.backButton,
          { top: topInset + 8, left: leftInset + 8 },
        ]}
        containerColor={theme.colors.surfaceVariant}
      />

      <ScrollView
        contentContainerStyle={[
          styles.content,
          {
            paddingTop: topInset + 64,
            paddingLeft: leftInset + 24,
          },
        ]}
      >
        <Text variant="headlineMedium" style={styles.heading}>
          How Smelter Editor works
        </Text>

        <Section title="Overview">
          <Para>
            Smelter Editor is a mobile remote control for a Smelter compositor
            server running on your local network. It lets you arrange video input
            streams into layers, adjust their positions and sizes, and trigger
            timeline events — all in real time.
          </Para>
        </Section>

        <Section title="Connecting">
          <Para>
            On the Join screen, enter the IP address and port of your Smelter
            server (e.g. 192.168.1.10:3001) and tap the connect icon, or tap a
            previously saved address from the list. Once the server responds, you
            will see the available rooms. Select one and tap Join Room.
          </Para>
          <Para>
            You can also scan a QR code generated by the server to fill in the
            server address and room ID automatically.
          </Para>
        </Section>

        <Section title="Layout screen">
          <Para>
            The Layout screen shows a grid representing the compositor canvas.
            Each cell corresponds to a fixed region of the output resolution. Drag
            and drop inputs between cells to reposition them. Use the settings
            panel (gear icon) to adjust the number of columns and rows.
          </Para>
          <Para>
            The grid factor setting (in app settings) controls how many pixels
            each grid cell represents. A lower value produces a finer grid; a
            higher value produces a coarser grid. Changes take effect the next
            time you join a room.
          </Para>
        </Section>

        <Section title="Inputs screen">
          <Para>
            The Inputs screen lists all active video inputs on the server. Tap an
            input to open its detail panel, where you can see the native
            resolution and layer assignment. Long-press to drag inputs into a
            different order.
          </Para>
        </Section>

        <Section title="Timeline screen">
          <Para>
            The Timeline screen controls playback of pre-configured timeline
            events on the server. Use the play/pause controls to start or stop
            playback. The current position is shown in real time.
          </Para>
        </Section>

        <Section title="Arrow navigation">
          <Para>
            When arrow navigation is enabled, physical left/right arrow buttons
            (or swipe gestures) cycle between the Layout, Inputs, and Timeline
            screens. This is useful when the device is mounted and touch is not
            convenient.
          </Para>
        </Section>

        <Section title="Saved servers">
          <Para>
            Server addresses you connect to are saved automatically and appear in
            the list on the Join screen. A health indicator shows whether each
            saved server is currently reachable. Tap the × button next to an
            address to remove it.
          </Para>
        </Section>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  backButton: {
    position: "absolute",
    zIndex: 10,
  },
  content: {
    paddingRight: 24,
    paddingBottom: 40,
    gap: 24,
  },
  heading: {
    marginBottom: 8,
  },
  section: {
    gap: 8,
  },
  sectionTitle: {
    marginBottom: 2,
  },
});
