import path from 'path';
import fs from 'fs';
import type { ShaderParamConfig, ShaderConfig, ShaderParam } from '../types';

export type { ShaderParamConfig, ShaderConfig };

type AvailableShader = {
  id: string;
  isActive: boolean;
  isVisible: boolean;
  name: string;
  description: string;
  shaderFile: string;
  params?: ShaderParam[];
};

export type PublicShader = AvailableShader & {
  iconSvg: string;
};

const AVAILABLE_SHADERS: AvailableShader[] = [
  {
    id: 'ascii-filter',
    isActive: true,
    isVisible: true,
    name: 'ASCII Filter',
    description: 'A filter that converts the input video to ASCII art.',
    shaderFile: 'ascii-filter.wgsl',
    params: [
      {
        name: 'glyph_size',
        type: 'number',
        minValue: 1,
        maxValue: 100,
        defaultValue: 10,
      },
      {
        name: 'gamma_correction',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.3,
      },
    ],
  },
  {
    id: 'grayscale',
    isActive: true,
    isVisible: true,
    name: 'Grayscale',
    description: 'A filter that converts the input video to grayscale.',
    shaderFile: 'grayscale.wgsl',
  },
  {
    id: 'opacity',
    isActive: true,
    isVisible: true,
    name: 'Opacity',
    description: 'A filter that sets the opacity of the input video.',
    shaderFile: 'opacity.wgsl',
    params: [
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'page-flip-1',
    isActive: true,
    isVisible: false,
    name: 'Page Flip',
    description:
      'A 3D page flip transition/filter with realistic shading and back tint option.',
    shaderFile: 'page-flip-1.wgsl',
    params: [
      {
        name: 'progress',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'direction',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'perspective',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'shadow_strength',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.35,
      },
      {
        name: 'back_tint',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.95,
      },
      {
        name: 'back_tint_strength',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.33,
      },
    ],
  },
  {
    id: 'brightness-contrast',
    isActive: true,
    isVisible: true,
    name: 'Brightness & Contrast',
    description:
      'A shader that adjusts the brightness and contrast of the input video.',
    shaderFile: 'brightness-contrast.wgsl',
    params: [
      {
        name: 'brightness',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'contrast',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'circle-mask-outline',
    isActive: true,
    isVisible: true,
    name: 'Wrapped Outline',
    description:
      'Masks the image to a circle with a given diameter and adds an outline with configurable width and hue.',
    shaderFile: 'circle-mask-outline.wgsl',
    params: [
      {
        name: 'circle_diameter',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.83,
      },
      {
        name: 'outline_width',
        type: 'number',
        minValue: 0,
        maxValue: 0.1,
        defaultValue: 0.01,
      },
      {
        name: 'outline_hue',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.44,
      },
      {
        name: 'circle_scale',
        type: 'number',
        minValue: 0.1,
        maxValue: 3,
        defaultValue: 1.03,
      },
      {
        name: 'circle_offset_x_px',
        type: 'number',
        minValue: -3000,
        maxValue: 3000,
        defaultValue: 0,
      },
      {
        name: 'circle_offset_y_px',
        type: 'number',
        minValue: -3000,
        maxValue: 3000,
        defaultValue: 0,
      },
      {
        name: 'wobble_x_amp_px',
        type: 'number',
        minValue: 0,
        maxValue: 1000,
        defaultValue: 20,
      },
      {
        name: 'wobble_x_freq',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 2.1,
      },
      {
        name: 'wobble_y_amp_px',
        type: 'number',
        minValue: 0,
        maxValue: 1000,
        defaultValue: 20,
      },
      {
        name: 'wobble_y_freq',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 1,
      },
      {
        name: 'trail_enable',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'trail_spawn_interval',
        type: 'number',
        minValue: 0.01,
        maxValue: 5,
        defaultValue: 0.31,
      },
      {
        name: 'trail_speed',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.53,
      },
      {
        name: 'trail_shrink_speed',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.05,
      },
      {
        name: 'trail_x_amplitude',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.03,
      },
      {
        name: 'trail_x_frequency',
        type: 'number',
        minValue: 0,
        maxValue: 5,
        defaultValue: 1.2,
      },
      {
        name: 'trail_count_f32',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 10,
      },
      {
        name: 'trail_opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.24,
      },
    ],
  },
  {
    id: 'remove-color',
    isActive: true,
    isVisible: true,
    name: 'Remove Color',
    description:
      'Removes the exact target RGB color by making it fully transparent.',
    shaderFile: 'remove-color.wgsl',
    params: [
      {
        name: 'target_color',
        type: 'color',
        defaultValue: '#1c1c35', // green by default (was r=0, g=1, b=0)
      },
      {
        name: 'tolerance',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.2,
      },
    ],
  },
  {
    id: 'color-key',
    isActive: true,
    isVisible: true,
    name: 'Color Key',
    description:
      'Advanced chroma key with matte generation, cleanup, spill suppression, and color correction (Ultra Key style).',
    shaderFile: 'color-key.wgsl',
    params: [
      {
        name: 'key_color',
        type: 'color',
        defaultValue: '#00ff00',
      },
      {
        name: 'tolerance',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.3,
      },
      {
        name: 'softness',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.1,
      },
      {
        name: 'highlight',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.1,
      },
      {
        name: 'shadow',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.16,
      },
      {
        name: 'pedestal',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.1,
      },
      {
        name: 'choke',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'contrast',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'mid_point',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'spill',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'spill_range',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'desaturate',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'saturation',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'hue',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'luminance',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'ultra-key',
    isActive: true,
    isVisible: true,
    name: 'Ultra Key',
    description:
      'HSV-based chroma key with independent hue/saturation/luminance tolerances, matte cleanup (erode, clip, gamma), spill suppression, and foreground correction.',
    shaderFile: 'ultra-key.wgsl',
    params: [
      {
        name: 'key_color',
        type: 'color',
        defaultValue: '#00ff00',
      },
      {
        name: 'hue_width',
        type: 'number',
        minValue: 0,
        maxValue: 0.5,
        defaultValue: 0.08,
      },
      {
        name: 'hue_softness',
        type: 'number',
        minValue: 0,
        maxValue: 0.3,
        defaultValue: 0.06,
      },
      {
        name: 'sat_threshold',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
      {
        name: 'sat_softness',
        type: 'number',
        minValue: 0,
        maxValue: 0.5,
        defaultValue: 0.1,
      },
      {
        name: 'luma_low',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.05,
      },
      {
        name: 'luma_high',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.95,
      },
      {
        name: 'luma_softness',
        type: 'number',
        minValue: 0,
        maxValue: 0.3,
        defaultValue: 0.05,
      },
      {
        name: 'erode',
        type: 'number',
        minValue: -0.5,
        maxValue: 0.5,
        defaultValue: 0,
      },
      {
        name: 'clip_low',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'clip_high',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'matte_gamma',
        type: 'number',
        minValue: 0.1,
        maxValue: 4,
        defaultValue: 1,
      },
      {
        name: 'despill',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'despill_balance',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'fg_brightness',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'fg_saturation',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'orbiting',
    isActive: true,
    isVisible: true,
    name: 'Orbiting',
    description: 'A shader that orbits the input video.',
    shaderFile: 'orbiting.wgsl',
    params: [
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'sprite_scale',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'orbit_radius',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'orbit_speed',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'copies_f32',
        type: 'number',
        minValue: 1,
        maxValue: 10,
        defaultValue: 3,
      },
      {
        name: 'colorize_amount',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'sun_rays',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 10,
      },
      {
        name: 'sun_anim_speed',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 3,
      },
      {
        name: 'sun_base_radius',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.35,
      },
      {
        name: 'sun_ray_amp',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.09,
      },
      {
        name: 'sun_softness',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.06,
      },
    ],
  },
  {
    id: 'sine-wave',
    isActive: true,
    isVisible: false,
    name: 'Sine Wave Distortion',
    description:
      'Applies a vertical sine-wave distortion along X with configurable amplitude, wavelength, speed and phase.',
    shaderFile: 'sine-wave.wgsl',
    params: [
      {
        name: 'amplitude_px',
        type: 'number',
        minValue: 0,
        maxValue: 400,
        defaultValue: 20,
      },
      {
        name: 'wavelength_px',
        type: 'number',
        minValue: 10,
        maxValue: 4000,
        defaultValue: 800,
      },
      {
        name: 'speed',
        type: 'number',
        minValue: -20,
        maxValue: 20,
        defaultValue: 2.5,
      },
      {
        name: 'phase',
        type: 'number',
        minValue: -6.283,
        maxValue: 6.283,
        defaultValue: 0,
      },
    ],
  },
  {
    id: 'star-streaks',
    isActive: true,
    isVisible: true,
    name: 'Star Streaks',
    description:
      'Adds animated, parameterized white streaks (warp-star effect) over the input, simulating fast motion through space.',
    shaderFile: 'star-streaks.wgsl',
    params: [
      {
        name: 'line_density',
        type: 'number',
        minValue: 1,
        maxValue: 200,
        defaultValue: 40,
      },
      {
        name: 'thickness_px',
        type: 'number',
        minValue: 0.5,
        maxValue: 10,
        defaultValue: 2,
      },
      {
        name: 'speed',
        type: 'number',
        minValue: 0,
        maxValue: 5,
        defaultValue: 0.8,
      },
      {
        name: 'jitter_amp_px',
        type: 'number',
        minValue: 0,
        maxValue: 50,
        defaultValue: 4,
      },
      {
        name: 'jitter_freq',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 1.5,
      },
      {
        name: 'dash_repeat',
        type: 'number',
        minValue: 0,
        maxValue: 50,
        defaultValue: 10,
      },
      {
        name: 'dash_duty',
        type: 'number',
        minValue: 0.0,
        maxValue: 1.0,
        defaultValue: 0.4,
      },
      {
        name: 'brightness',
        type: 'number',
        minValue: 0.0,
        maxValue: 3.0,
        defaultValue: 0.5,
      },
    ],
  },
  {
    id: 'soft-shadow',
    isActive: true,
    isVisible: true,
    name: 'Soft Shadow',
    description:
      'Adds a soft, slightly animated shadow behind the input. Color, opacity, offset and blur are configurable.',
    shaderFile: 'soft-shadow.wgsl',
    params: [
      {
        name: 'shadow_r',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.0,
      },
      {
        name: 'shadow_g',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.0,
      },
      {
        name: 'shadow_b',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.0,
      },
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'offset_x_px',
        type: 'number',
        minValue: -200,
        maxValue: 200,
        defaultValue: 8,
      },
      {
        name: 'offset_y_px',
        type: 'number',
        minValue: -200,
        maxValue: 200,
        defaultValue: 8,
      },
      {
        name: 'blur_px',
        type: 'number',
        minValue: 0,
        maxValue: 200,
        defaultValue: 6,
      },
      {
        name: 'anim_amp_px',
        type: 'number',
        minValue: 0,
        maxValue: 30,
        defaultValue: 2,
      },
      {
        name: 'anim_speed',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 2,
      },
    ],
  },
  {
    id: 'alpha-stroke',
    isActive: true,
    isVisible: true,
    name: 'Alpha Stroke',
    description:
      'Draws an outline wherever transparent and opaque pixels meet, with configurable width, softness, and color.',
    shaderFile: 'alpha-stroke.wgsl',
    params: [
      {
        name: 'stroke_width_px',
        type: 'number',
        minValue: 0,
        maxValue: 100,
        defaultValue: 66,
      },
      {
        name: 'softness_px',
        type: 'number',
        minValue: 0,
        maxValue: 50,
        defaultValue: 31.5,
      },
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      { name: 'stroke_color', type: 'color', defaultValue: '#000000' },
    ],
  },
  {
    id: 'sw-hologram',
    isActive: true,
    isVisible: true,
    name: 'SW Hologram',
    description:
      'Star Wars style hologram effect with scanlines, flicker, chromatic aberration, and blue tint.',
    shaderFile: 'sw-hologram.wgsl',
    params: [
      {
        name: 'tint_r',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.25,
      },
      {
        name: 'tint_g',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.6,
      },
      {
        name: 'tint_b',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1.0,
      },
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.92,
      },
      {
        name: 'scanline_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.65,
      },
      {
        name: 'scanline_density',
        type: 'number',
        minValue: 10,
        maxValue: 500,
        defaultValue: 127.6,
      },
      {
        name: 'scanline_speed',
        type: 'number',
        minValue: 0,
        maxValue: 50,
        defaultValue: 37.0,
      },
      {
        name: 'flicker_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.69,
      },
      {
        name: 'flicker_speed',
        type: 'number',
        minValue: 0,
        maxValue: 30,
        defaultValue: 8,
      },
      {
        name: 'chromatic_aberration_px',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 2,
      },
      {
        name: 'noise_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.0,
      },
      {
        name: 'jitter_x_px',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 2.2,
      },
      {
        name: 'jitter_y_px',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 0.5,
      },
      {
        name: 'jitter_speed',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 2.2,
      },
      {
        name: 'glow_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.09,
      },
      {
        name: 'edge_glow_width',
        type: 'number',
        minValue: 0,
        maxValue: 0.5,
        defaultValue: 0.1,
      },
      {
        name: 'brightness',
        type: 'number',
        minValue: 0.5,
        maxValue: 5,
        defaultValue: 2.93,
      },
      {
        name: 'bloom_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 0.42,
      },
      {
        name: 'bloom_radius',
        type: 'number',
        minValue: 1,
        maxValue: 50,
        defaultValue: 32.36,
      },
    ],
  },
  {
    id: 'perspective',
    isActive: true,
    isVisible: true,
    name: 'Perspective',
    description:
      'Applies perspective transformation to the content, making it appear to recede into the distance (vanishing point at bottom).',
    shaderFile: 'perspective.wgsl',
    params: [
      {
        name: 'perspective',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'scale',
        type: 'number',
        minValue: 0.1,
        maxValue: 3,
        defaultValue: 1.0,
      },
      {
        name: 'rotation',
        type: 'number',
        minValue: -3.14159,
        maxValue: 3.14159,
        defaultValue: 0.0,
      },
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1.0,
      },
    ],
  },
  {
    id: 'grid-overlay',
    isActive: true,
    isVisible: false,
    name: 'Grid Overlay',
    description:
      'Procedurally generates a grid overlay with configurable cell count, gap size and line color.',
    shaderFile: 'grid-overlay.wgsl',
    params: [
      {
        name: 'cells_x',
        type: 'number',
        minValue: 1,
        maxValue: 200,
        defaultValue: 20,
      },
      {
        name: 'cells_y',
        type: 'number',
        minValue: 1,
        maxValue: 200,
        defaultValue: 20,
      },
      {
        name: 'gap',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 1,
      },
      {
        name: 'line_r',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.75,
      },
      {
        name: 'line_g',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.75,
      },
      {
        name: 'line_b',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.75,
      },
      {
        name: 'line_a',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1.0,
      },
    ],
  },
  {
    id: 'blur',
    isActive: true,
    isVisible: true,
    name: 'Blur',
    description:
      'Gaussian blur with configurable radius, strength, directional mode, alpha preservation, and quality (sample count).',
    shaderFile: 'blur.wgsl',
    params: [
      {
        name: 'radius',
        type: 'number',
        minValue: 0,
        maxValue: 50,
        defaultValue: 5,
      },
      {
        name: 'strength',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'direction_x',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'direction_y',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'preserve_alpha',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'quality',
        type: 'number',
        minValue: 1,
        maxValue: 8,
        defaultValue: 4,
      },
    ],
  },
  {
    id: 'hsl-adjust',
    isActive: true,
    isVisible: true,
    name: 'HSL Adjust',
    description:
      'Adjust hue, saturation, and lightness. Supports colorize mode and blend with original.',
    shaderFile: 'hsl-adjust.wgsl',
    params: [
      {
        name: 'hue_shift',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'saturation',
        type: 'number',
        minValue: -1,
        maxValue: 2,
        defaultValue: 0,
      },
      {
        name: 'lightness',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'colorize_enable',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'colorize_hue',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'colorize_saturation',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'mix_amount',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'vignette',
    isActive: true,
    isVisible: true,
    name: 'Vignette',
    description:
      'Darkens edges of the frame with configurable intensity, radius, softness, roundness, color, center offset, and opacity.',
    shaderFile: 'vignette.wgsl',
    params: [
      {
        name: 'intensity',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'radius',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'softness',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 0.5,
      },
      {
        name: 'roundness',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'color_r',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'color_g',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'color_b',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'center_x',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'center_y',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'chromatic-aberration',
    isActive: true,
    isVisible: true,
    name: 'Chromatic Aberration',
    description:
      'Splits RGB channels with configurable offset, angle, falloff from center, per-channel multipliers, and optional animation.',
    shaderFile: 'chromatic-aberration.wgsl',
    params: [
      {
        name: 'offset_px',
        type: 'number',
        minValue: 0,
        maxValue: 50,
        defaultValue: 5,
      },
      {
        name: 'angle',
        type: 'number',
        minValue: 0,
        maxValue: 6.283,
        defaultValue: 0,
      },
      {
        name: 'falloff',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 1,
      },
      {
        name: 'center_x',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'center_y',
        type: 'number',
        minValue: -1,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'r_multiplier',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'g_multiplier',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'b_multiplier',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
      {
        name: 'animated',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'anim_speed',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 2,
      },
    ],
  },
  {
    id: 'sharpen',
    isActive: true,
    isVisible: true,
    name: 'Sharpen',
    description:
      'Unsharp mask sharpening with strength, radius, threshold, edge detection preview, and detail boost.',
    shaderFile: 'sharpen.wgsl',
    params: [
      {
        name: 'strength',
        type: 'number',
        minValue: 0,
        maxValue: 5,
        defaultValue: 1,
      },
      {
        name: 'radius_px',
        type: 'number',
        minValue: 0.5,
        maxValue: 10,
        defaultValue: 1,
      },
      {
        name: 'threshold',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'edge_detect_mix',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'detail_boost',
        type: 'number',
        minValue: 0,
        maxValue: 2,
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'snake-event-highlight',
    isActive: true,
    isVisible: true,
    name: 'Snake Event Highlight',
    description:
      'Visual effect overlay for snake game events. Supports pulse glow, flash, shake, color shift, ripple, vignette, chromatic burst, and pixelate effects.',
    shaderFile: 'snake-event-highlight.wgsl',
    params: [
      {
        name: 'effect_type',
        type: 'number',
        minValue: 0,
        maxValue: 8,
        defaultValue: 1,
      },
      {
        name: 'intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.7,
      },
      { name: 'effect_color', type: 'color', defaultValue: '#ff4400' },
      {
        name: 'progress',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
    ],
  },
  {
    id: 'transition-slide',
    isActive: true,
    isVisible: false,
    name: 'Transition Slide',
    description:
      'Slide transition: offsets UV coordinates based on progress and direction.',
    shaderFile: 'transition-slide.wgsl',
    params: [
      {
        name: 'progress',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'direction',
        type: 'number',
        minValue: 0,
        maxValue: 3,
        defaultValue: 0,
      },
    ],
  },
  {
    id: 'transition-wipe',
    isActive: true,
    isVisible: false,
    name: 'Transition Wipe',
    description: 'Wipe transition: hard-edge reveal along the horizontal axis.',
    shaderFile: 'transition-wipe.wgsl',
    params: [
      {
        name: 'progress',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'direction',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
    ],
  },
  {
    id: 'transition-dissolve',
    isActive: true,
    isVisible: false,
    name: 'Transition Dissolve',
    description: 'Dissolve transition: noise-based pixel dissolve effect.',
    shaderFile: 'transition-dissolve.wgsl',
    params: [
      {
        name: 'progress',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
    ],
  },
  {
    id: 'cyberpunk-hands',
    isActive: true,
    isVisible: false,
    name: 'Cyberpunk Hands',
    description:
      'Neon glow hand skeleton overlay driven by MediaPipe Hands landmarks.',
    shaderFile: 'cyberpunk-hands.wgsl',
  },
  {
    id: 'comic-book',
    isActive: true,
    isVisible: true,
    name: 'Comic Book',
    description:
      'Multi-scale ink outlines, gamma-aware posterization, CMYK Ben-Day halftone dots, paper warmth, and animated speed lines for an authentic comic book / manga look.',
    shaderFile: 'comic-book.wgsl',
    params: [
      { name: 'ink_color', type: 'color', defaultValue: '#000000' },
      {
        name: 'edge_strength',
        type: 'number',
        minValue: 0,
        maxValue: 5,
        defaultValue: 2.0,
      },
      {
        name: 'edge_thickness',
        type: 'number',
        minValue: 0.1,
        maxValue: 5,
        defaultValue: 2.0,
      },
      {
        name: 'color_levels',
        type: 'number',
        minValue: 2,
        maxValue: 16,
        defaultValue: 5,
      },
      {
        name: 'saturation_boost',
        type: 'number',
        minValue: 0,
        maxValue: 3,
        defaultValue: 1.6,
      },
      {
        name: 'halftone_size',
        type: 'number',
        minValue: 0,
        maxValue: 30,
        defaultValue: 4,
      },
      {
        name: 'halftone_strength',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.5,
      },
      {
        name: 'ink_smoothness',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.3,
      },
      {
        name: 'paper_warmth',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
      {
        name: 'brightness',
        type: 'number',
        minValue: 0.5,
        maxValue: 2,
        defaultValue: 1.15,
      },
      {
        name: 'speed_lines',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'speed_line_density',
        type: 'number',
        minValue: 5,
        maxValue: 100,
        defaultValue: 30,
      },
    ],
  },
  {
    id: 'neon-glow',
    isActive: true,
    isVisible: true,
    name: 'Neon Glow',
    description:
      'Cyberpunk neon glow effect — detects edges via Sobel filter and renders them as bright, blooming neon light with configurable color and pulse animation.',
    shaderFile: 'neon-glow.wgsl',
    params: [
      { name: 'glow_color', type: 'color', defaultValue: '#ff00ff' },
      {
        name: 'edge_threshold',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
      {
        name: 'glow_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 3,
        defaultValue: 1.5,
      },
      {
        name: 'bloom_radius',
        type: 'number',
        minValue: 1,
        maxValue: 30,
        defaultValue: 8,
      },
      {
        name: 'background_dim',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.3,
      },
      {
        name: 'pulse_speed',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 2.0,
      },
      {
        name: 'pulse_amount',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.2,
      },
    ],
  },
  {
    id: 'cyber-glitch',
    isActive: true,
    isVisible: true,
    name: 'Cyber Glitch',
    description:
      'Digital corruption effect — multi-directional slice displacement, RGB channel splitting, block artifacts with color inversion, and CRT scanlines like a hacked cyberpunk terminal.',
    shaderFile: 'cyber-glitch.wgsl',
    params: [
      {
        name: 'slice_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.3,
      },
      {
        name: 'slice_count',
        type: 'number',
        minValue: 1,
        maxValue: 50,
        defaultValue: 8,
      },
      {
        name: 'rgb_split',
        type: 'number',
        minValue: 0,
        maxValue: 30,
        defaultValue: 5,
      },
      {
        name: 'noise_intensity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
      {
        name: 'block_glitch',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.4,
      },
      {
        name: 'speed',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 3.0,
      },
      {
        name: 'scanline_alpha',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
    ],
  },
  {
    id: 'neon-edge',
    isActive: true,
    isVisible: true,
    name: 'Neon Edge',
    description:
      'Tron-like neon wireframe effect — renders video as bright glowing edge outlines on a dark background with optional hue-cycling animation.',
    shaderFile: 'neon-edge.wgsl',
    params: [
      { name: 'edge_color', type: 'color', defaultValue: '#00ffff' },
      {
        name: 'edge_threshold',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.1,
      },
      {
        name: 'line_brightness',
        type: 'number',
        minValue: 0,
        maxValue: 5,
        defaultValue: 2.5,
      },
      {
        name: 'background_opacity',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.1,
      },
      {
        name: 'glow_spread',
        type: 'number',
        minValue: 0,
        maxValue: 20,
        defaultValue: 4,
      },
      {
        name: 'pulse_speed',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 1.5,
      },
      {
        name: 'color_shift_speed',
        type: 'number',
        minValue: 0,
        maxValue: 5,
        defaultValue: 0.0,
      },
    ],
  },
  {
    id: 'hex-grid',
    isActive: true,
    isVisible: true,
    name: 'Hex Grid',
    description:
      'Cyberpunk HUD visor effect — hexagonal pixelation with glowing neon borders, configurable hex size, border color, and pulsing glow animation.',
    shaderFile: 'hex-grid.wgsl',
    params: [
      {
        name: 'hex_size',
        type: 'number',
        minValue: 5,
        maxValue: 100,
        defaultValue: 20,
      },
      { name: 'border_color', type: 'color', defaultValue: '#00ff88' },
      {
        name: 'border_width',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.08,
      },
      {
        name: 'border_glow',
        type: 'number',
        minValue: 0,
        maxValue: 3,
        defaultValue: 1.2,
      },
      {
        name: 'background_dim',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
      {
        name: 'pulse_speed',
        type: 'number',
        minValue: 0,
        maxValue: 10,
        defaultValue: 1.0,
      },
      {
        name: 'pulse_amount',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0.15,
      },
    ],
  },
  {
    id: 'crop',
    isActive: true,
    isVisible: false,
    name: 'Crop',
    description:
      'Internal shader that masks edges of the input to transparent, used for crop functionality.',
    shaderFile: 'crop.wgsl',
    params: [
      {
        name: 'crop_top',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'crop_left',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'crop_right',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
      {
        name: 'crop_bottom',
        type: 'number',
        minValue: 0,
        maxValue: 1,
        defaultValue: 0,
      },
    ],
  },
];

class ShadersController {
  public get shaders(): PublicShader[] {
    const baseIconsDir = path.resolve(__dirname, '../../shaders/icons');
    return AVAILABLE_SHADERS.filter((shader) => shader.isActive).map(
      (shader) => {
        const iconPath = path.join(baseIconsDir, `${shader.id}.svg`);
        let iconSvg = '';
        try {
          iconSvg = fs.readFileSync(iconPath, { encoding: 'utf-8' });
        } catch {
          iconSvg =
            '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><rect width="24" height="24" fill="#888"/></svg>';
        }
        return { ...shader, iconSvg };
      },
    );
  }

  public getShaderById(shaderId: string): AvailableShader | undefined {
    return AVAILABLE_SHADERS.find(
      (shader) => shader.id === shaderId && shader.isActive,
    );
  }
}

const shadersController = new ShadersController();
export default shadersController;
