const API='http://localhost:3001';
const created=await (await fetch(`${API}/room`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initInputs:[],skipDefaultInputs:true,resolution:{width:1920,height:1080}})})).json();
const roomId=created.roomId;
const j=m=>JSON.stringify(m);
const ws=new WebSocket(`ws://localhost:3001/room/${roomId}/ws`);
const states=[];
ws.addEventListener('message',m=>{try{const ev=JSON.parse(String(m.data));if(ev.type==='kbt_state')states.push(ev);}catch{}});
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
ws.send(j({type:'kbt_spectate'}));
ws.send(j({type:'kbt_join',name:'FOTKA'}));
await new Promise(r=>setTimeout(r,400));
const TINY=Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/yQALCAABAAEBAREA/8wABgAQEAX/2gAIAQEAAD8A0s8g/9k=','base64');
const fd=new FormData();
fd.append('name','FOTKA');
fd.append('photo',new Blob([TINY],{type:'image/jpeg'}),'photo.jpg');
const t0=Date.now();
const up=await fetch(`${API}/room/${roomId}/kettlebell-tournament/photo`,{method:'POST',body:fd});
console.log('upload:',up.status,JSON.stringify(await up.json()));
await new Promise(r=>setTimeout(r,600));
const withPhoto=states.filter(s=>s.players?.some(p=>p.photoUrl));
console.log('kbt_state broadcasts total:',states.length,'with photoUrl:',withPhoto.length);
if(withPhoto.length)console.log('first with photo after upload: +'+(Date.now()-t0-600)+'ms window, player:',JSON.stringify(withPhoto[0].players.map(p=>({name:p.name,photoUrl:p.photoUrl}))));
ws.close();
await fetch(`${API}/room/${roomId}`,{method:'DELETE'});
