/**
 * OB Van — the all-Smelter question bank for the AI-contestant show
 * (`config.quiz.bank = 'smelter'`).
 *
 * Every fact here is checkable against the official docs (smelter.dev /
 * `.agents/skills/smelter-ts-docs/`), and the same material feeds the
 * contestants' study pack (`llm/smelterContext.ts`) — so a prepared model
 * SHOULD get most of these, while the distractors stay plausible enough
 * that it won't get all of them. Asked in bank order, easy → hard.
 */
import type { QuizQuestion } from './quizQuestions';

export const SMELTER_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 's01',
    q: 'Who builds Smelter?',
    answers: [
      'Software Mansion',
      'Smelting Industries',
      'The WebRTC WG',
      'A Twitch mod team',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's02',
    q: 'How do you describe a Smelter scene in the TypeScript SDK?',
    answers: [
      'YAML manifests',
      'React components',
      'SQL queries',
      'Hand-written H.264',
    ],
    correct: 'B',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's03',
    q: 'What language are Smelter shaders written in?',
    answers: ['GLSL', 'HLSL', 'WGSL', 'CUDA'],
    correct: 'C',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's04',
    q: 'Which component arranges children in equal-sized, non-overlapping tiles?',
    answers: ['View', 'Rescaler', 'SlideShow', 'Tiles'],
    correct: 'D',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's05',
    q: 'How many children does a Rescaler take?',
    answers: [
      'Exactly one',
      'Up to four',
      'Any number',
      'None — it wraps inputs by id',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's06',
    q: 'A registered input shows up in the scene through which component?',
    answers: ['WebView', 'InputStream', 'Show', 'Image'],
    correct: 'B',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's07',
    q: 'Which runtime package runs Smelter with no server at all, in the browser?',
    answers: [
      '@swmansion/smelter-node',
      '@swmansion/smelter-web-client',
      '@swmansion/smelter-web-wasm',
      '@swmansion/smelter-edge',
    ],
    correct: 'C',
    topic: 'smelter',
    difficulty: 1,
  },
  {
    id: 's08',
    q: "What is Rescaler's default rescaleMode?",
    answers: ['fill', 'stretch', 'crop', 'fit'],
    correct: 'D',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's09',
    q: 'In live processing, Smelter keeps the pipeline synchronized to…',
    answers: [
      'The wall clock',
      'The GPU clock',
      'The fastest input',
      'NTP only',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's10',
    q: 'Offline processing runs…',
    answers: [
      'One frame per second',
      'As fast as the hardware allows',
      'Only at night',
      'At exactly real time',
    ],
    correct: 'B',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's11',
    q: 'Which component plays an MP4 file with NO registration step?',
    answers: ['InputStream', 'Show', 'Mp4', 'Image'],
    correct: 'C',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's12',
    q: 'An MP4 input supports which codecs?',
    answers: [
      'VP9 video, Vorbis audio',
      'H264 video, AAC audio',
      'AV1 video, FLAC audio',
      'MJPEG video, PCM audio',
    ],
    correct: 'B',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's13',
    q: "What is the WHIP server's default port?",
    answers: ['8080', '1935', '3000', '9000'],
    correct: 'D',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's14',
    q: 'The rtmp_server input listens by default on port…',
    answers: ['1935', '9000', '443', '554'],
    correct: 'A',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's15',
    q: 'A whep_client input accepts which audio codec?',
    answers: ['AAC only', 'Opus only', 'MP3 only', 'Any codec FFmpeg knows'],
    correct: 'B',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's16',
    q: 'For a transition to animate a View across a scene update, the View must keep…',
    answers: ['The same id', 'The same children', 'A zIndex', 'A key prop'],
    correct: 'A',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's17',
    q: 'The default easing function of a transition is…',
    answers: ['bounce', 'ease-in-out', 'linear', 'cubic_bezier'],
    correct: 'C',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's18',
    q: 'Which hook blocks offline rendering until an async task resolves?',
    answers: [
      'useAfterTimestamp',
      'useInputStreams',
      'useAudioInput',
      'useBlockingTask',
    ],
    correct: 'D',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's19',
    q: 'Which hook mixes the audio of an input without rendering it on screen?',
    answers: [
      'useAudioInput',
      'useInputStreams',
      'useBlockingTask',
      'useSound',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's20',
    q: 'Which required prop does Text insist on?',
    answers: ['color', 'fontFamily', 'fontSize', 'maxWidth'],
    correct: 'C',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's21',
    q: 'WebView renders websites inside the scene using…',
    answers: [
      'A headless Firefox',
      'Embedded Chromium',
      'An iframe shader',
      'Server-side screenshots',
    ],
    correct: 'B',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's22',
    q: 'How do you chain two shader effects on the same video?',
    answers: [
      'Comma-separated shaderIds',
      'A ShaderChain component',
      'Register them as one WGSL file',
      'Nest one Shader inside the other',
    ],
    correct: 'D',
    topic: 'smelter',
    difficulty: 2,
  },
  {
    id: 's23',
    q: 'The shaderParam struct reaches WGSL as a uniform at…',
    answers: [
      '@group(1) @binding(0)',
      '@group(0) @binding(0)',
      '@group(2) @binding(1)',
      'push constants',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's24',
    q: 'On web-wasm, a shader receives how many input textures?',
    answers: ['Sixteen', 'One', 'Four', 'As many as it declares'],
    correct: 'B',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's25',
    q: 'Registering an mp4 input requires exactly one of…',
    answers: [
      'loop or seekMs',
      'offsetMs or required',
      'url or serverPath',
      'videoId or audioId',
    ],
    correct: 'C',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's26',
    q: 'Rule of thumb for the `required` flag on inputs:',
    answers: [
      'All offline, none live',
      'All live, none offline',
      'Always on',
      'Only for audio',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's27',
    q: "Without offsetMs, an input's timing is derived from…",
    answers: [
      'The wall clock at register',
      'The previous input',
      'Its container metadata',
      'The first packet arrival',
    ],
    correct: 'D',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's28',
    q: 'seek() lives on which input handle?',
    answers: [
      'WhipInputHandle',
      'Mp4InputHandle',
      'Every InputHandle',
      'RtpInputHandle',
    ],
    correct: 'B',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's29',
    q: 'Which output serves one composed program to MANY WebRTC viewers?',
    answers: ['whip_client', 'rtp_stream', 'whep_server', 'canvas'],
    correct: 'C',
    topic: 'smelter',
    difficulty: 3,
  },
  {
    id: 's30',
    q: 'A Tiles transition animates…',
    answers: [
      'Reorder, add and remove',
      'Tile size changes',
      'Background color',
      'Nothing — Tiles never animate',
    ],
    correct: 'A',
    topic: 'smelter',
    difficulty: 3,
  },
];
